package com.memhunter.agent.scoring;

/** Recognises classes generated by the JVM's own mechanisms (reflection accessors, lambdas, proxies). */
public final class JvmGeneratedClasses {

    private JvmGeneratedClasses() {}

    /** Pre-compiled pattern for bare {@code $ProxyN} names (no package prefix). */
    private static final java.util.regex.Pattern PROXY = java.util.regex.Pattern.compile("\\$Proxy\\d+");

    private static final String[] PREFIXES = {
        "sun.reflect.GeneratedMethodAccessor",
        "sun.reflect.GeneratedConstructorAccessor",
        "sun.reflect.GeneratedSerializationConstructorAccessor",
        "jdk.internal.reflect.Generated",
        "com.sun.proxy.$Proxy",
        "sun.proxy.$Proxy"
    };

    public static boolean isJvmGenerated(String className) {
        if (className == null) return false;
        for (String p : PREFIXES) {
            if (className.startsWith(p)) return true;
        }
        if (className.contains("$$Lambda$")) return true;
        if (PROXY.matcher(className).matches()) return true;
        return false;
    }
}
